# Generated by Django 5.2.11 on 2026-04-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creataed_at',
            new_name='created_at',
        ),
    ]
